# Generated by Django 4.2 on 2025-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.FileField(upload_to='partners'),
        ),
    ]
