# Generated by Django 4.2 on 2025-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_partner_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
