# Generated by Django 4.2 on 2025-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_partner_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media_zone/images'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.FileField(upload_to='media_zone/partners'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='media_zone/teams'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media_zone/videos'),
        ),
    ]
