# Generated by Django 4.2 on 2025-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
