# Generated by Django 4.2 on 2025-07-11 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('client', '0001_initial'), ('client', '0002_alter_client_description')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('cancelled', 'cancelled'), ('done', 'done')], max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
