from core.settings.base import env


AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME') # faqat konteyner nomi!
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')  # HTTPS bilan!
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_S3_FILE_OVERWRITE = env('AWS_S3_FILE_OVERWRITE')
AWS_QUERYSTRING_AUTH = env("AWS_QUERYSTRING_AUTH")
AWS_DEFAULT_ACL = env('AWS_DEFAULT_ACL')
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')
