# Generated by Django 5.2.3 on 2025-07-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='type',
            field=models.CharField(choices=[('INCOME', 'income'), ('EXPENCE', 'expence')], max_length=15),
        ),
    ]
