# Generated by Django 4.2 on 2025-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_alter_estimate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
