# Generated by Django 5.2.3 on 2025-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monthly_income',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
