# Generated by Django 4.2 on 2025-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
