# Generated by Django 4.2 on 2025-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomorder_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='prepayment_price',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
