# Generated by Django 4.2 on 2025-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_price_per_hour',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
