# Generated by Django 4.2 on 2025-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_image_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
