# Generated by Django 4.2 on 2025-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='type',
            field=models.CharField(choices=[('crm', 'crm'), ('web', 'web')], default='crm', max_length=3),
        ),
    ]
