# Generated by Django 4.2 on 2025-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomorder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
