# Generated by Django 4.2 on 2025-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_roomorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='servis_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='servis_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
